# Use postgres/example user/password credentials
version: "3.1"

services:
    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: ${ApplicationContext__PG__USER}
            POSTGRES_PASSWORD: ${ApplicationContext__PG__PASSWORD}
            POSTGRES_DB: ${ApplicationContext__PG__DB}
        volumes:
            - 'db_data:/var/lib/postgresql/data'
        ports:
            - ${ApplicationContext__PG__PORT}:5432

    adminer:
        image: adminer
        restart: always
        ports:
            - ${ADMINER_PORT}:8080
volumes:
  db_data:
