name: Deploy dev build

on:
  workflow_dispatch:
  workflow_run:
    workflows: [backend-test]
    types: [completed]
    branches: [main]

jobs:
  deploy:
    if: |
        github.event.workflow_run.conclusion == 'success'
        || github.event_name == 'workflow_dispatch'
    concurrency:
      group: test-env-deploy
      cancel-in-progress: true
    permissions:
      deployments: write
    runs-on: ubuntu-latest
    steps:
      - uses: dentarg/fly@v1
        with:
          fly-token: ${{ secrets.FLY_API_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
